version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phrase-generator-api
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${SERVER_PORT}", "--reload"]
